#!/usr/bin/env bash

set -e

CLI_JAR="./build/libs/apiman-cli.jar"

if [[ ! -f ${CLI_JAR} ]]; then
    chmod u+x ./gradlew
    ./gradlew clean shadowJar
    clear
fi

# look for -i parameter indicating STDIN
USE_STDIN=0
for ARG in $@; do
    if [[ "-i" == "${ARG}" ]]; then
        USE_STDIN=1
        break
    fi
done

# pipe STDIN into command
if [[ 1 == ${USE_STDIN} ]]; then
    read STDIN
    echo ${STDIN} | java -jar ${CLI_JAR} "$@"

else
    java -jar ${CLI_JAR} "$@"
fi
